# Generated by Django 5.0.14 on 2025-05-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_content_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
